apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: souravbwebapp 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: souravbwebapp 
    spec:
      containers:
        - name: souravbwebapp 
          image: my1acr.azurecr.io/souravbwebapp
          ports:
          - containerPort: 5000
